script:
# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
# Tagging
  - docker tag udagram-api-feed doanthi159/udagram-api-feed:v1
  - docker tag udagram-api-user doanthi159/udagram-api-user:v1
  - docker tag udagram-frontend doanthi159/udagram-frontend:v1
  - docker tag udagram-reverseproxy doanthi159/udagram-reverseproxy:v1
# Do similar for other three images```
# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push doanthi159/udagram-api-feed:v1
  - docker push doanthi159/udagram-api-user:v1
  - docker push doanthi159/udagram-frontend:v1
  - docker push doanthi159/udagram-reverseproxy:v1